import type { Metadata } from "next";
import { Montserrat,  Source_Code_Pro} from "next/font/google";
import { AuthProvider } from "./context/authContext";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic']
});

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic']
});

export const metadata: Metadata = {
  title: "SentinelAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`mx-4 md:mx-12 lg:mx-20 px-4 sm:px-6 md:px-8 bg-gradient-to-b from-[#163936] to-[#296639] min-h-screen ${montserrat.className} antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
