export const testData = [
  {
    id: 'txn_jill_001',
    amount: 3200,
    currency: 'usd',
    customer: 'cus_jill',
    billing_details: {
      name: 'Jill Smith',
      email: 'jill@example.com',
      phone: '555-101-2233',
      address: {
        line1: '1001 Maple St',
        city: 'Denver',
        state: 'CO',
        postal_code: '80201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_visa' },
  },
  {
    id: 'txn_jill_002',
    amount: 3400,
    currency: 'usd',
    customer: 'cus_jill',
    billing_details: {
      name: 'Jill Smith',
      email: 'jill@example.com',
      phone: '555-101-2233',
      address: {
        line1: '1001 Maple St',
        city: 'Denver',
        state: 'CO',
        postal_code: '80201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_mastercard' },
  },
  {
    id: 'txn_jill_003',
    amount: 3100,
    currency: 'usd',
    customer: 'cus_jill',
    billing_details: {
      name: 'Jill Smith',
      email: 'jill@example.com',
      phone: '555-101-2233',
      address: {
        line1: '1001 Maple St',
        city: 'Denver',
        state: 'CO',
        postal_code: '80201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_discover' },
  },
  {
    id: 'txn_jill_004',
    amount: 3300,
    currency: 'usd',
    customer: 'cus_jill',
    billing_details: {
      name: 'Jill Smith',
      email: 'jill@example.com',
      phone: '555-101-2233',
      address: {
        line1: '1001 Maple St',
        city: 'Denver',
        state: 'CO',
        postal_code: '80201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_visa' },
  },
  {
    id: 'txn_jill_005',
    amount: 3500,
    currency: 'usd',
    customer: 'cus_jill',
    billing_details: {
      name: 'Jill Smith',
      email: 'jill@example.com',
      phone: '555-101-2233',
      address: {
        line1: '1001 Maple St',
        city: 'Denver',
        state: 'CO',
        postal_code: '80201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_amex' },
  },
  {
    id: 'txn_grace_001',
    amount: 6800,
    currency: 'usd',
    customer: 'cus_grace',
    billing_details: {
      name: 'Grace Lee',
      email: 'grace@example.com',
      phone: '555-707-3344',
      address: {
        line1: '99 Ocean Blvd',
        city: 'Miami',
        state: 'FL',
        postal_code: '33101',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_visa' },
  },
  {
    id: 'txn_grace_002',
    amount: 7000,
    currency: 'usd',
    customer: 'cus_grace',
    billing_details: {
      name: 'Grace Lee',
      email: 'grace@example.com',
      phone: '555-707-3344',
      address: {
        line1: '222 Bay Ave',
        city: 'Boston',
        state: 'MA',
        postal_code: '02118',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_mastercard' },
  },
  {
    id: 'txn_grace_003',
    amount: 6700,
    currency: 'usd',
    customer: 'cus_grace',
    billing_details: {
      name: 'Grace Lee',
      email: 'grace@example.com',
      phone: '555-707-3344',
      address: {
        line1: '14 Tech Way',
        city: 'Seattle',
        state: 'WA',
        postal_code: '98101',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_discover' },
  },
  {
    id: 'txn_grace_004',
    amount: 6900,
    currency: 'usd',
    customer: 'cus_grace',
    billing_details: {
      name: 'Grace Lee',
      email: 'grace@example.com',
      phone: '555-707-3344',
      address: {
        line1: '88 Windmill Ln',
        city: 'Austin',
        state: 'TX',
        postal_code: '73301',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_visa' },
  },
  {
    id: 'txn_grace_005',
    amount: 7100,
    currency: 'usd',
    customer: 'cus_grace',
    billing_details: {
      name: 'Grace Lee',
      email: 'grace@example.com',
      phone: '555-707-3344',
      address: {
        line1: '45 Ridge Rd',
        city: 'Phoenix',
        state: 'AZ',
        postal_code: '85001',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_amex' },
  },
  {
    id: 'txn_grace_006',
    amount: 6550,
    currency: 'usd',
    customer: 'cus_grace',
    billing_details: {
      name: 'Grace Lee',
      email: 'grace@example.com',
      phone: '555-707-3344',
      address: {
        line1: '500 Sunset Blvd',
        city: 'Los Angeles',
        state: 'CA',
        postal_code: '90001',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_mastercard' },
  },
  {
    id: 'txn_grace_007',
    amount: 6400,
    currency: 'usd',
    customer: 'cus_grace',
    billing_details: {
      name: 'Grace Lee',
      email: 'grace@example.com',
      phone: '555-707-3344',
      address: {
        line1: '39 High St',
        city: 'Philadelphia',
        state: 'PA',
        postal_code: '19104',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_discover' },
  },
  {
    id: 'txn_frank_001',
    amount: 19000,
    currency: 'usd',
    customer: 'cus_frank',
    billing_details: {
      name: 'Frank Ruiz',
      email: 'frank@example.com',
      phone: '555-900-1122',
      address: {
        line1: '123 Fraud Ln',
        city: 'Brooklyn',
        state: 'NY',
        postal_code: '11201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_amex' },
  },
  {
    id: 'txn_frank_002',
    amount: 19500,
    currency: 'usd',
    customer: 'cus_frank',
    billing_details: {
      name: 'Frank Ruiz',
      email: 'frank@example.com',
      phone: '555-900-1122',
      address: {
        line1: '123 Fraud Ln',
        city: 'Brooklyn',
        state: 'NY',
        postal_code: '11201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_chargeDeclined' },
  },
  {
    id: 'txn_frank_003',
    amount: 20200,
    currency: 'usd',
    customer: 'cus_frank',
    billing_details: {
      name: 'Frank Ruiz',
      email: 'frank@example.com',
      phone: '555-900-1122',
      address: {
        line1: '123 Fraud Ln',
        city: 'Brooklyn',
        state: 'NY',
        postal_code: '11201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_discover' },
  },
  {
    id: 'txn_frank_004',
    amount: 18900,
    currency: 'usd',
    customer: 'cus_frank',
    billing_details: {
      name: 'Frank Ruiz',
      email: 'frank@example.com',
      phone: '555-900-1122',
      address: {
        line1: '123 Fraud Ln',
        city: 'Brooklyn',
        state: 'NY',
        postal_code: '11201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_visa' },
  },
  {
    id: 'txn_frank_005',
    amount: 21400,
    currency: 'usd',
    customer: 'cus_frank',
    billing_details: {
      name: 'Frank Ruiz',
      email: 'frank@example.com',
      phone: '555-900-1122',
      address: {
        line1: '123 Fraud Ln',
        city: 'Brooklyn',
        state: 'NY',
        postal_code: '11201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_amex' },
  },
  {
    id: 'txn_frank_006',
    amount: 20900,
    currency: 'usd',
    customer: 'cus_frank',
    billing_details: {
      name: 'Frank Ruiz',
      email: 'frank@example.com',
      phone: '555-900-1122',
      address: {
        line1: '123 Fraud Ln',
        city: 'Brooklyn',
        state: 'NY',
        postal_code: '11201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_chargeDeclined' },
  },
  {
    id: 'txn_frank_007',
    amount: 19300,
    currency: 'usd',
    customer: 'cus_frank',
    billing_details: {
      name: 'Frank Ruiz',
      email: 'frank@example.com',
      phone: '555-900-1122',
      address: {
        line1: '123 Fraud Ln',
        city: 'Brooklyn',
        state: 'NY',
        postal_code: '11201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_discover' },
  },
  {
    id: 'txn_frank_008',
    amount: 22000,
    currency: 'usd',
    customer: 'cus_frank',
    billing_details: {
      name: 'Frank Ruiz',
      email: 'frank@example.com',
      phone: '555-900-1122',
      address: {
        line1: '123 Fraud Ln',
        city: 'Brooklyn',
        state: 'NY',
        postal_code: '11201',
        country: 'US',
      },
    },
    status: 'succeeded',
    payment_method: { type: 'card', token: 'tok_mastercard' },
  },
];
